easy_admin:
    site_name: Foodsharing
    entities:
        User:
            class: App\Entity\User
            form:  # <-- 'form' is applied to both 'new' and 'edit' views
                fields:
                    - 'firstName'
                    - 'lastName'
                    - 'email'
                    - 'activated'
                    - 'createdAt'
                    - 'updatedAt'
        Location:
            class: App\Entity\Location

        Product:
            class: App\Entity\Product
            form:
                fields:
                    - 'title'
                    - 'description'
                    - 'status'
                    - { property: 'givenAway', type: 'checkbox'}
                    - 'createdAt'
                    - 'updatedAt'
