easy_admin:
    disabled_actions: ['new']
    site_name: Foodsharing
    entities:
        User:
            class: App\Entity\User
            form:  # <-- 'form' is applied to both 'new' and 'edit' views
                fields:
                    - 'firstName'
                    - 'lastName'
                    - 'email'
                    - 'activated'

        Product:
            class: App\Entity\Product
            form:
                fields:
                    - 'title'
                    - 'description'
                    - 'status'
                    - { property: 'givenAway', type: 'checkbox'}

        Location:
            disabled_actions: ['delete']
            class: App\Entity\Location